"use client";
import {useMemo,useState} from "react";
import {Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {Activity,ArrowDownRight,ArrowUpRight,BookOpen,BrainCircuit,BriefcaseBusiness,ChevronRight,Clock3,Database,FlaskConical,Gauge,Landmark,LineChart,Newspaper,Play,RefreshCcw,ShieldCheck,Target,WalletCards} from "lucide-react";
import {ASSETS,calculatePortfolioMetrics,deserializeGame,getResearchView,serializeGame,type GameMode,type OrderSide,type OrderType,type PlayerOrder} from "@market-architect/engine";
import {REGIME_LABELS} from "@market-architect/market-data";
import {useGameStore} from "@/lib/store";
import {Badge} from "@/components/ui/badge";import {Button} from "@/components/ui/button";import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";import {Input} from "@/components/ui/input";
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:n<10?4:2}).format(n);
const pct=(n:number)=>`${n>=0?"+":""}${(n*100).toFixed(2)}%`;
const metricColor=(n:number)=>n>=0?"text-[#73f2b2]":"text-[#ff8d92]";

export function MarketGame(){
 const {game,selectedSymbol,setSelectedSymbol,advance,newRun,load}=useGameStore();
 const [tab,setTab]=useState<"market"|"portfolio"|"research"|"academy">("market");
 const [side,setSide]=useState<OrderSide>("buy"),[type,setType]=useState<OrderType>("market"),[qty,setQty]=useState("1"),[price,setPrice]=useState("");
 const [seed,setSeed]=useState(game.seed),[mode,setMode]=useState<GameMode>(game.mode),[notice,setNotice]=useState("");
 const metrics=useMemo(()=>calculatePortfolioMetrics(game),[game]); const selected=game.assets[selectedSymbol]!; const def=ASSETS.find(a=>a.symbol===selectedSymbol)!; const research=getResearchView(game,selectedSymbol);
 const chartData=selected.history.map((value,index)=>({index:index+1,value}));
 const order=():PlayerOrder|undefined=>{const q=Number(qty);if(!Number.isFinite(q)||q<=0){setNotice("Enter a positive quantity.");return;}const p=Number(price);const o:PlayerOrder={id:`manual-${Date.now()}`,symbol:selectedSymbol,side,type,quantity:q,createdTick:game.tick};if(type==="limit")o.limitPrice=p;if(type==="stop-loss"||type==="take-profit")o.triggerPrice=p;advance([o]);setNotice(`${type.replace("-"," ")} ${side} submitted for ${selectedSymbol}.`);return o};
 const saveFile=()=>{const blob=new Blob([serializeGame(game)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`market-architect-${game.runId}.json`;a.click();URL.revokeObjectURL(url)};
 const loadFile=(file?:File)=>{if(!file)return;file.text().then(t=>{load(deserializeGame(t));setNotice("Versioned save loaded.")}).catch(()=>setNotice("Save file could not be loaded."))};
 return <main className="grid-bg min-h-screen px-3 py-3 sm:px-5 lg:px-7">
  <div className="mx-auto max-w-[1680px]">
   <header className="mb-3 flex flex-col gap-3 rounded-2xl border border-[#254237] bg-[#08130f]/90 p-4 backdrop-blur-xl lg:flex-row lg:items-center lg:justify-between">
    <div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-2xl bg-[#73f2b2] text-[#07100d]"><Landmark size={23}/></div><div><div className="flex items-center gap-2"><h1 className="text-xl font-black tracking-tight sm:text-2xl">Market Architect</h1><Badge>Simulation v1</Badge></div><p className="text-xs text-[#829c90]">Regime analysis · portfolio construction · deterministic audit trail</p></div></div>
    <div className="flex flex-wrap items-center gap-2"><Badge className="border-[#73f2b2]/35 text-[#aef8d1]">{REGIME_LABELS[game.regime]}</Badge><Badge>Day {game.tick+1} · {['Mon','Tue','Wed','Thu','Fri'][game.dayOfWeek-1]}</Badge><Button variant="outline" size="sm" onClick={saveFile}><Database size={14}/>Save</Button><label className="inline-flex h-8 cursor-pointer items-center gap-2 rounded-xl border border-[#2d4a3e] bg-[#0c1713] px-3 text-xs font-semibold text-[#dcebe4] hover:border-[#73f2b2]/50"><RefreshCcw size={14}/>Load<input className="hidden" type="file" accept="application/json" onChange={e=>loadFile(e.target.files?.[0])}/></label><Button size="sm" onClick={()=>advance()}><Play size={14}/>Advance day</Button></div>
   </header>
   <section className="mb-3 grid grid-cols-2 gap-2 lg:grid-cols-7">
    <Metric icon={<WalletCards/>} label="Net worth" value={money(metrics.netWorth)} sub={pct(metrics.totalReturn)} positive={metrics.totalReturn>=0}/>
    <Metric icon={<Landmark/>} label="Cash" value={money(game.cash)} sub={`${(game.cash/metrics.netWorth*100).toFixed(1)}% liquidity`} positive={game.cash/metrics.netWorth>=.08}/>
    <Metric icon={<Activity/>} label="Day P&L" value={money(metrics.dayPnl)} sub="mark-to-market" positive={metrics.dayPnl>=0}/>
    <Metric icon={<Clock3/>} label="Week P&L" value={money(metrics.weekPnl)} sub="rolling 5 sessions" positive={metrics.weekPnl>=0}/>
    <Metric icon={<Gauge/>} label="Risk score" value={`${metrics.riskScore.toFixed(0)}/100`} sub={`${(metrics.volatility*100).toFixed(1)}% vol · ${(metrics.concentration*100).toFixed(0)}% concentration`} positive={metrics.riskScore<65}/>
    <Metric icon={<Target/>} label="Max drawdown" value={pct(metrics.maxDrawdown)} sub="since run start" positive={metrics.maxDrawdown>-.08}/>
    <Metric icon={<LineChart/>} label="Alpha" value={pct(metrics.alpha)} sub={`benchmark ${pct(metrics.benchmarkReturn)}`} positive={metrics.alpha>=0}/>
   </section>
   <div className="mb-3 flex gap-1 overflow-x-auto rounded-2xl border border-[#213d32] bg-[#09140f] p-1">{([["market","Market"],["portfolio","Portfolio"],["research","Research Desk"],["academy","Academy & Career"]] as const).map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`whitespace-nowrap rounded-xl px-4 py-2 text-sm font-semibold ${tab===id?'bg-[#1b3128] text-[#9ff4c7]':'text-[#789286] hover:text-white'}`}>{label}</button>)}</div>
   {tab==="market"&&<div className="grid gap-3 xl:grid-cols-[1.2fr_.85fr_.8fr]">
    <div className="space-y-3"><Card><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle>{selectedSymbol} · {def.name}</CardTitle><p className="mt-1 text-xs text-[#789286]">{def.description}</p></div><div className="text-right"><div className="mono text-2xl font-bold">{money(selected.price)}</div><div className={`text-xs ${metricColor(selected.price/selected.previousClose-1)}`}>{pct(selected.price/selected.previousClose-1)}</div></div></CardHeader><CardContent><div className="h-[290px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#73f2b2" stopOpacity={.35}/><stop offset="95%" stopColor="#73f2b2" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#183329" vertical={false}/><XAxis dataKey="index" hide/><YAxis domain={['auto','auto']} orientation="right" tick={{fill:'#6f8d80',fontSize:11}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:'#0a1712',border:'1px solid #2b4d3f',borderRadius:12}} formatter={(v)=>money(Number(v))}/><Area type="monotone" dataKey="value" stroke="#73f2b2" fill="url(#fill)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></CardContent></Card>
    <Card><CardHeader><CardTitle>Asset universe</CardTitle></CardHeader><CardContent className="p-0"><div className="scrollbar max-h-[450px] overflow-auto"><table className="w-full text-left text-sm"><thead className="sticky top-0 bg-[#0d1a15] text-[10px] uppercase tracking-widest text-[#6f8b7e]"><tr><th className="px-4 py-3">Asset</th><th>Class</th><th className="text-right">Price</th><th className="pr-4 text-right">Day</th></tr></thead><tbody>{ASSETS.map(a=>{const m=game.assets[a.symbol]!,r=m.price/m.previousClose-1;return <tr key={a.symbol} onClick={()=>setSelectedSymbol(a.symbol)} className={`cursor-pointer border-t border-[#193127] hover:bg-[#13251e] ${selectedSymbol===a.symbol?'bg-[#163026]':''}`}><td className="px-4 py-3"><div className="font-bold">{a.symbol}</div><div className="text-[11px] text-[#6f8b7e]">{a.name}</div></td><td className="text-xs capitalize text-[#9ab0a5]">{a.assetClass.replace('-',' ')}</td><td className="mono text-right">{money(m.price)}</td><td className={`mono pr-4 text-right ${metricColor(r)}`}>{pct(r)}</td></tr>})}</tbody></table></div></CardContent></Card></div>
    <div className="space-y-3"><Card><CardHeader><CardTitle>Order ticket</CardTitle></CardHeader><CardContent className="space-y-3"><div className="grid grid-cols-2 gap-2"><Button variant={side==='buy'?'default':'outline'} onClick={()=>setSide('buy')}>Buy</Button><Button variant={side==='sell'?'danger':'outline'} onClick={()=>setSide('sell')}>Sell</Button></div><div><label className="mb-1 block text-[10px] uppercase tracking-widest text-[#718d80]">Order type</label><select value={type} onChange={e=>setType(e.target.value as OrderType)} className="h-10 w-full rounded-xl border border-[#2a493c] bg-[#08110e] px-3 text-sm"><option value="market">Market</option><option value="limit">Limit</option><option value="stop-loss">Stop loss</option><option value="take-profit">Take profit</option></select></div><div><label className="mb-1 block text-[10px] uppercase tracking-widest text-[#718d80]">Quantity</label><Input value={qty} onChange={e=>setQty(e.target.value)} inputMode="decimal"/></div>{type!=="market"&&<div><label className="mb-1 block text-[10px] uppercase tracking-widest text-[#718d80]">{type==='limit'?'Limit':'Trigger'} price</label><Input value={price} onChange={e=>setPrice(e.target.value)} inputMode="decimal" placeholder={selected.price.toFixed(2)}/></div>}<div className="rounded-xl border border-[#203d31] bg-[#08120f] p-3 text-xs text-[#8fa99d]"><div className="flex justify-between"><span>Bid / Ask</span><span className="mono">{money(selected.bid)} / {money(selected.ask)}</span></div><div className="mt-2 flex justify-between"><span>Estimated base spread</span><span>{def.spreadBps} bps</span></div><div className="mt-2 flex justify-between"><span>Liquidity per tick</span><span>{money(def.liquidity*.08)}</span></div></div><Button className="w-full" onClick={order}>Review & submit</Button>{notice&&<p className="rounded-xl bg-[#12271f] p-3 text-xs text-[#a4c7b7]">{notice}</p>}</CardContent></Card>
    <Card><CardHeader><CardTitle>Market microstructure</CardTitle></CardHeader><CardContent className="space-y-3 text-xs"><Info label="Fractional support" value={def.fractional?'Enabled':'Whole units'}/><Info label="Modeled volume" value={selected.volume.toLocaleString()}/><Info label="Open orders" value={String(game.openOrders.filter(o=>o.symbol===selectedSymbol).length)}/><Info label="Position" value={`${game.positions[selectedSymbol]?.quantity??0} units`}/></CardContent></Card></div>
    <div className="space-y-3"><Card><CardHeader className="flex flex-row items-center gap-2"><Newspaper size={16}/><CardTitle>Why markets moved</CardTitle></CardHeader><CardContent className="space-y-3">{game.news.length?game.news.slice(0,5).map(n=><article key={n.id} className="rounded-xl border border-[#213e32] bg-[#0a1511] p-3"><div className="text-sm font-semibold">{n.headline}</div><p className="mt-1 text-xs leading-relaxed text-[#87a095]">{n.summary}</p><div className="mt-2 text-[10px] uppercase tracking-widest text-[#6f8d80]">Severity {(n.severity*100).toFixed(0)} · Tick {n.createdTick}</div></article>):<Empty text="Advance the simulation to generate causal market news."/>}</CardContent></Card><Rivals game={game}/></div>
   </div>}
   {tab==="portfolio"&&<Portfolio game={game} metrics={metrics}/>} {tab==="research"&&<Research game={game} selectedSymbol={selectedSymbol} research={research}/>} {tab==="academy"&&<Academy game={game} seed={seed} setSeed={setSeed} mode={mode} setMode={setMode} newRun={newRun}/>}
   <footer className="mt-4 flex flex-col gap-2 border-t border-[#1c352b] py-4 text-xs text-[#617c6f] sm:flex-row sm:justify-between"><span>Educational simulation only. Not investment advice. No real accounts, wallets, tokens, or market feeds.</span><span className="mono">Run {game.runId} · schema v{game.schemaVersion} · seed {game.seed}</span></footer>
  </div>
 </main>
}
function Metric({icon,label,value,sub,positive}:{icon:React.ReactNode;label:string;value:string;sub:string;positive:boolean}){return <Card className="min-h-[112px]"><CardContent className="p-4"><div className="flex items-center justify-between text-[#779287]"><span className="text-[10px] font-semibold uppercase tracking-[.14em]">{label}</span><span className="[&>svg]:size-4">{icon}</span></div><div className="mono mt-3 text-lg font-bold sm:text-xl">{value}</div><div className={`mt-1 flex items-center gap-1 text-[11px] ${positive?'text-[#73f2b2]':'text-[#ff8d92]'}`}>{positive?<ArrowUpRight size={12}/>:<ArrowDownRight size={12}/>} {sub}</div></CardContent></Card>}
function Info({label,value}:{label:string;value:string}){return <div className="flex justify-between border-b border-[#1d372d] pb-2 last:border-0"><span className="text-[#718b7f]">{label}</span><span className="mono text-[#dbe9e2]">{value}</span></div>}
function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed border-[#2a493c] p-5 text-center text-xs text-[#708a7e]">{text}</div>}
function Rivals({game}:{game:any}){return <Card><CardHeader className="flex flex-row items-center gap-2"><BriefcaseBusiness size={16}/><CardTitle>Rival funds</CardTitle></CardHeader><CardContent className="space-y-2">{game.rivals.map((f:any)=><div key={f.id} className="rounded-xl border border-[#203d31] p-3"><div className="flex items-center justify-between"><div><div className="text-sm font-semibold">{f.name}</div><div className="text-[10px] uppercase tracking-widest text-[#6e897c]">{f.style} · top {f.topExposure}</div></div><div className="text-right"><div className="mono font-bold">{f.nav.toFixed(2)}</div><div className={`text-xs ${metricColor(f.dailyReturn)}`}>{f.dailyReturn>=0?'+':''}{f.dailyReturn.toFixed(2)}%</div></div></div><div className="mt-2 h-1.5 rounded-full bg-[#172d24]"><div className="h-full rounded-full bg-[#73f2b2]" style={{width:`${f.risk}%`}}/></div></div>)}</CardContent></Card>}
function Portfolio({game,metrics}:{game:any;metrics:any}){return <div className="grid gap-3 lg:grid-cols-[1fr_1.1fr]"><Card><CardHeader><CardTitle>Allocation & concentration</CardTitle></CardHeader><CardContent className="space-y-3">{metrics.allocation.map((a:any)=><div key={a.label}><div className="mb-1 flex justify-between text-xs"><span>{a.label}</span><span className="mono">{money(a.value)} · {a.pct.toFixed(1)}%</span></div><div className="h-2 rounded-full bg-[#172d24]"><div className="h-full rounded-full bg-[#73f2b2]" style={{width:`${Math.min(a.pct,100)}%`}}/></div></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Transaction history</CardTitle></CardHeader><CardContent className="p-0"><div className="scrollbar max-h-[520px] overflow-auto"><table className="w-full text-sm"><thead className="sticky top-0 bg-[#0d1a15] text-[10px] uppercase tracking-widest text-[#6f8b7e]"><tr><th className="px-4 py-3 text-left">Trade</th><th className="text-right">Qty</th><th className="text-right">Execution</th><th className="pr-4 text-right">Fee</th></tr></thead><tbody>{game.transactions.length?game.transactions.map((t:any)=><tr key={t.id} className="border-t border-[#193127]"><td className="px-4 py-3"><div className={`font-bold ${t.side==='buy'?'text-[#73f2b2]':'text-[#ff8d92]'}`}>{t.side.toUpperCase()} {t.symbol}</div><div className="text-[10px] uppercase tracking-widest text-[#6f8b7e]">{t.orderType} · tick {t.tick}</div></td><td className="mono text-right">{t.quantity}</td><td className="mono text-right">{money(t.executionPrice)}</td><td className="mono pr-4 text-right">{money(t.fee)}</td></tr>):<tr><td colSpan={4} className="p-6"><Empty text="No completed trades yet."/></td></tr>}</tbody></table></div></CardContent></Card></div>}
function Research({game,selectedSymbol,research}:{game:any;selectedSymbol:string;research:any}){
 const chain=game.assets[selectedSymbol]?.onChain;
 const audit=game.auditLog[0]?.assetRecords.find((a:any)=>a.symbol===selectedSymbol);
 return <div className="grid gap-3 lg:grid-cols-2">
  <Card>
   <CardHeader className="flex flex-row items-center gap-2"><BrainCircuit size={17}/><CardTitle>Deterministic research desk · {selectedSymbol}</CardTitle></CardHeader>
   <CardContent className="space-y-3">
    <Case title="Bull case" tone="good" text={research.bullCase}/>
    <Case title="Bear case" tone="bad" text={research.bearCase}/>
    <div className="rounded-xl border border-[#24483a] bg-[#0b1914] p-4">
     <div className="flex justify-between"><span className="text-sm font-semibold">Confidence</span><span className="mono text-[#73f2b2]">{research.confidence}%</span></div>
     <div className="mt-2 h-2 rounded-full bg-[#173027]"><div className="h-full rounded-full bg-[#73f2b2]" style={{width:`${research.confidence}%`}}/></div>
     <h4 className="mt-4 text-[10px] uppercase tracking-widest text-[#718b7f]">Evidence</h4>
     {research.evidence.map((e:string)=><div className="mt-2 flex gap-2 text-xs text-[#a6bcb1]" key={e}><ChevronRight size={13}/>{e}</div>)}
     <h4 className="mt-4 text-[10px] uppercase tracking-widest text-[#718b7f]">Invalidation conditions</h4>
     {research.invalidation.map((e:string)=><div className="mt-2 flex gap-2 text-xs text-[#d2b8a3]" key={e}><ShieldCheck size={13}/>{e}</div>)}
    </div>
   </CardContent>
  </Card>
  <Card>
   <CardHeader><CardTitle>Price-change audit</CardTitle></CardHeader>
   <CardContent>
    {audit ? <div className="space-y-2">{audit.components.map((c:any)=><div key={c.label} className="rounded-xl border border-[#203d31] p-3"><div className="flex justify-between"><span className="text-sm font-semibold">{c.label}</span><span className={`mono text-xs ${metricColor(c.contribution)}`}>{pct(c.contribution)}</span></div><p className="mt-1 text-xs text-[#7f9a8d]">{c.explanation}</p></div>)}</div> : <Empty text="Advance one day to produce the first audit record."/>}
   </CardContent>
  </Card>
  {chain ? <Card className="lg:col-span-2">
   <CardHeader><CardTitle>Simulated on-chain metrics</CardTitle></CardHeader>
   <CardContent className="grid grid-cols-2 gap-2 md:grid-cols-6"><Chain label="TVL" value={`$${chain.tvl}B`}/><Chain label="Active users" value={chain.activeUsers.toLocaleString()}/><Chain label="Fees" value={`$${chain.fees}M`}/><Chain label="Staking ratio" value={`${chain.stakingRatio}%`}/><Chain label="Exchange flows" value={`${chain.exchangeFlows}M`}/><Chain label="30d unlock" value={`${chain.unlockPct30d}%`}/></CardContent>
  </Card> : null}
 </div>
}
function Case({title,text,tone}:{title:string;text:string;tone:'good'|'bad'}){return <div className={`rounded-xl border p-4 ${tone==='good'?'border-[#2f5b47] bg-[#10251d]':'border-[#5a3638] bg-[#251416]'}`}><div className={`text-xs font-bold uppercase tracking-widest ${tone==='good'?'text-[#73f2b2]':'text-[#ff969b]'}`}>{title}</div><p className="mt-2 text-sm leading-relaxed text-[#c4d4cc]">{text}</p></div>}
function Chain({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-[#203d31] bg-[#091510] p-3"><div className="text-[10px] uppercase tracking-widest text-[#718b7f]">{label}</div><div className="mono mt-2 font-bold">{value}</div></div>}
function Academy({game,seed,setSeed,mode,setMode,newRun}:{game:any;seed:string;setSeed:(v:string)=>void;mode:GameMode;setMode:(v:GameMode)=>void;newRun:(s:string,m:GameMode)=>void}){return <div className="grid gap-3 lg:grid-cols-[1fr_.8fr]"><Card><CardHeader className="flex flex-row items-center gap-2"><BookOpen size={17}/><CardTitle>Learning track</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2"><Lesson icon={<Gauge/>} title="Risk before return" text="Use concentration, drawdown, and volatility together rather than judging a portfolio by profit alone."/><Lesson icon={<FlaskConical/>} title="Regime transmission" text="Trace first-order winners, second-order constraints, and the macro variables connecting them."/><Lesson icon={<Newspaper/>} title="Narrative discipline" text="Every move has an audit decomposition; compare the headline with the actual modeled drivers."/><Lesson icon={<Target/>} title="Order mechanics" text="Spreads, fees, slippage, liquidity, and triggers make execution quality part of strategy."/></CardContent></Card><Card><CardHeader><CardTitle>Start a deterministic run</CardTitle></CardHeader><CardContent className="space-y-3"><div><label className="mb-1 block text-[10px] uppercase tracking-widest text-[#718d80]">Seed</label><Input value={seed} onChange={e=>setSeed(e.target.value)}/></div><div className="grid grid-cols-2 gap-2"><Button variant={mode==='academy'?'default':'outline'} onClick={()=>setMode('academy')}><BookOpen size={15}/>Academy</Button><Button variant={mode==='career'?'default':'outline'} onClick={()=>setMode('career')}><BriefcaseBusiness size={15}/>Career</Button></div><div className="rounded-xl border border-[#203d31] bg-[#08120f] p-3 text-xs leading-relaxed text-[#8fa99d]">Academy emphasizes explanations and guided learning. Career uses the same engine but frames performance against rival funds and benchmark alpha.</div><Button className="w-full" onClick={()=>newRun(seed,mode)}>Create new run</Button><div className="text-[11px] text-[#687f74]">Current run: {game.seed} · {game.mode} · {game.tick} completed ticks</div></CardContent></Card></div>}
function Lesson({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="rounded-xl border border-[#203d31] bg-[#091510] p-4"><div className="mb-3 flex size-9 items-center justify-center rounded-xl bg-[#17352a] text-[#73f2b2]">{icon}</div><div className="font-semibold">{title}</div><p className="mt-2 text-xs leading-relaxed text-[#819b8f]">{text}</p></div>}
