import type { AssetDefinition } from "@market-architect/shared";
import { sensitivity } from "./helper";

export const ASSETS_2: AssetDefinition[] = [
  {symbol:"UTIL",name:"Northline Utilities",assetClass:"stock",sector:"Utilities",description:"Regulated electricity and transmission operator.",initialPrice:41,volatility:.009,baseDrift:.00025,liquidity:48_000_000,spreadBps:6,fractional:true,benchmarkWeight:.04,exposures:{"ai-boom":.15,"sticky-inflation":-.15,"rate-cut-rally":.65,"credit-stress":.2,"supply-shock":.15,"crypto-risk-on":-.1},macroSensitivity:sensitivity(.1,-.1,-.9,-.1,.2,0)},
  {symbol:"TECH",name:"Frontier Tech ETF",assetClass:"etf",sector:"Technology",description:"Diversified technology-sector basket.",initialPrice:118,volatility:.019,baseDrift:.0006,liquidity:260_000_000,spreadBps:3,fractional:true,benchmarkWeight:.1,exposures:{"ai-boom":1,"sticky-inflation":-.35,"rate-cut-rally":.7,"credit-stress":-.75,"supply-shock":-.25,"crypto-risk-on":.2},macroSensitivity:sensitivity(1,-.3,-.9,-.65,-.1,.15)},
  {symbol:"ENRG",name:"Energy Producers ETF",assetClass:"etf",sector:"Energy",description:"Integrated energy and services basket.",initialPrice:72,volatility:.021,baseDrift:.0003,liquidity:170_000_000,spreadBps:4,fractional:true,benchmarkWeight:.06,exposures:{"ai-boom":.05,"sticky-inflation":.55,"rate-cut-rally":.1,"credit-stress":-.2,"supply-shock":1.45,"crypto-risk-on":.05},macroSensitivity:sensitivity(.5,.45,.05,-.2,1.5,0)},
  {symbol:"FINX",name:"Financial Sector ETF",assetClass:"etf",sector:"Financials",description:"Banks, insurers, and capital markets firms.",initialPrice:88,volatility:.017,baseDrift:.00035,liquidity:190_000_000,spreadBps:4,fractional:true,benchmarkWeight:.07,exposures:{"ai-boom":.2,"sticky-inflation":.15,"rate-cut-rally":.25,"credit-stress":-1.25,"supply-shock":-.3,"crypto-risk-on":.1},macroSensitivity:sensitivity(.75,.05,.25,-1.4,-.1,.05)},
  {symbol:"REIT",name:"Urban Assets ETF",assetClass:"etf",sector:"Real Estate",description:"Public real-estate and infrastructure assets.",initialPrice:36,volatility:.015,baseDrift:.00025,liquidity:85_000_000,spreadBps:6,fractional:true,benchmarkWeight:.04,exposures:{"ai-boom":.1,"sticky-inflation":-.35,"rate-cut-rally":1.1,"credit-stress":-.8,"supply-shock":-.15,"crypto-risk-on":0},macroSensitivity:sensitivity(.4,-.25,-1.35,-.7,-.1,0)},
];
