import type { AssetDefinition } from "@market-architect/shared";
import { sensitivity } from "./helper";

export const ASSETS_3: AssetDefinition[] = [
  {symbol:"GOVT",name:"7Y Sovereign Bond",assetClass:"bond",sector:"Government Bonds",description:"Intermediate-duration sovereign bond fund.",initialPrice:100,volatility:.006,baseDrift:.00015,liquidity:420_000_000,spreadBps:2,fractional:true,benchmarkWeight:.08,exposures:{"ai-boom":-.25,"sticky-inflation":-.9,"rate-cut-rally":1.4,"credit-stress":.7,"supply-shock":-.4,"crypto-risk-on":-.25},macroSensitivity:sensitivity(-.2,-.9,-1.8,.25,-.15,-.05)},
  {symbol:"CORP",name:"Investment Grade Credit",assetClass:"bond",sector:"Corporate Bonds",description:"Investment-grade corporate bond portfolio.",initialPrice:102,volatility:.007,baseDrift:.0002,liquidity:230_000_000,spreadBps:4,fractional:true,benchmarkWeight:.06,exposures:{"ai-boom":.05,"sticky-inflation":-.55,"rate-cut-rally":.9,"credit-stress":-1.15,"supply-shock":-.3,"crypto-risk-on":0},macroSensitivity:sensitivity(.15,-.5,-1.15,-1.4,-.1,0)},
  {symbol:"GOLD",name:"Gold Trust",assetClass:"commodity",sector:"Precious Metals",description:"Gold exposure used as a real-rate and stress hedge.",initialPrice:198,volatility:.012,baseDrift:.0002,liquidity:300_000_000,spreadBps:3,fractional:true,benchmarkWeight:.05,exposures:{"ai-boom":-.1,"sticky-inflation":.55,"rate-cut-rally":.7,"credit-stress":.85,"supply-shock":.55,"crypto-risk-on":-.1},macroSensitivity:sensitivity(-.1,.45,-.7,.35,.15,-.05)},
  {symbol:"OIL",name:"Crude Basket",assetClass:"commodity",sector:"Energy",description:"Diversified crude-oil futures basket.",initialPrice:76,volatility:.026,baseDrift:.0001,liquidity:210_000_000,spreadBps:7,fractional:true,benchmarkWeight:.04,exposures:{"ai-boom":.1,"sticky-inflation":.6,"rate-cut-rally":.15,"credit-stress":-.6,"supply-shock":1.8,"crypto-risk-on":.05},macroSensitivity:sensitivity(.8,.5,.05,-.45,1.7,0)},
  {symbol:"COPR",name:"Copper Basket",assetClass:"commodity",sector:"Industrial Metals",description:"Copper exposure tied to global manufacturing and electrification.",initialPrice:49,volatility:.021,baseDrift:.00025,liquidity:95_000_000,spreadBps:8,fractional:true,benchmarkWeight:.035,exposures:{"ai-boom":.45,"sticky-inflation":.3,"rate-cut-rally":.45,"credit-stress":-.9,"supply-shock":.75,"crypto-risk-on":.05},macroSensitivity:sensitivity(1.25,.2,-.25,-.55,.4,0)},
];
