import type { AssetDefinition } from "@market-architect/shared";
import { sensitivity } from "./helper";

export const ASSETS_4: AssetDefinition[] = [
  {symbol:"WHEAT",name:"Agriculture Basket",assetClass:"commodity",sector:"Agriculture",description:"Global grain and soft-commodity exposure.",initialPrice:31,volatility:.024,baseDrift:.00005,liquidity:52_000_000,spreadBps:11,fractional:true,benchmarkWeight:.025,exposures:{"ai-boom":0,"sticky-inflation":.45,"rate-cut-rally":.05,"credit-stress":-.15,"supply-shock":1.25,"crypto-risk-on":0},macroSensitivity:sensitivity(.15,.5,.05,-.1,.6,0)},
  {symbol:"BTCX",name:"Digital Reserve Asset",assetClass:"crypto",sector:"Crypto",description:"Scarce, reserve-style crypto asset with macro liquidity sensitivity.",initialPrice:67_500,volatility:.042,baseDrift:.001,liquidity:520_000_000,spreadBps:8,fractional:true,benchmarkWeight:.045,exposures:{"ai-boom":.3,"sticky-inflation":-.2,"rate-cut-rally":.85,"credit-stress":-1.05,"supply-shock":-.1,"crypto-risk-on":1.7},macroSensitivity:sensitivity(.45,-.1,-.7,-.6,-.05,1.6)},
  {symbol:"ETHX",name:"Programmable Network Asset",assetClass:"crypto",sector:"Crypto",description:"Network asset linked to application activity and staking demand.",initialPrice:3_420,volatility:.052,baseDrift:.0011,liquidity:340_000_000,spreadBps:10,fractional:true,benchmarkWeight:.03,exposures:{"ai-boom":.35,"sticky-inflation":-.25,"rate-cut-rally":.95,"credit-stress":-1.25,"supply-shock":-.1,"crypto-risk-on":2},macroSensitivity:sensitivity(.55,-.1,-.75,-.7,-.05,1.85)},
  {symbol:"USDQ",name:"Simulated Stablecoin",assetClass:"stablecoin",sector:"Crypto Cash",description:"Dollar-like settlement asset with modeled depeg risk but no blockchain connection.",initialPrice:1,volatility:.0012,baseDrift:0,liquidity:800_000_000,spreadBps:2,fractional:true,benchmarkWeight:.005,exposures:{"ai-boom":0,"sticky-inflation":0,"rate-cut-rally":0,"credit-stress":-.05,"supply-shock":0,"crypto-risk-on":0},macroSensitivity:sensitivity(0,0,0,-.05,0,.05)},
  {symbol:"TBTK",name:"Tokenized Treasury Fund",assetClass:"tokenized-treasury",sector:"Crypto Yield",description:"Simulated short-duration government yield token.",initialPrice:10,volatility:.0018,baseDrift:.00012,liquidity:120_000_000,spreadBps:5,fractional:true,benchmarkWeight:.01,exposures:{"ai-boom":0,"sticky-inflation":.1,"rate-cut-rally":.15,"credit-stress":.1,"supply-shock":0,"crypto-risk-on":.05},macroSensitivity:sensitivity(0,.05,.15,.05,0,.1)}
];
