import type { AssetDefinition } from "@market-architect/shared";
import { sensitivity } from "./helper";

export const ASSETS_1: AssetDefinition[] = [
  {symbol:"AION",name:"Aion Compute",assetClass:"stock",sector:"AI Infrastructure",description:"Accelerator chips and data-center systems.",initialPrice:142,volatility:.028,baseDrift:.0008,liquidity:150_000_000,spreadBps:5,fractional:true,benchmarkWeight:.09,exposures:{"ai-boom":1.35,"sticky-inflation":-.5,"rate-cut-rally":.75,"credit-stress":-.9,"supply-shock":-.35,"crypto-risk-on":.25},macroSensitivity:sensitivity(1.2,-.4,-1.1,-.8,-.15,.2)},
  {symbol:"GRID",name:"GridWorks",assetClass:"stock",sector:"Infrastructure",description:"Power-grid modernization and industrial automation.",initialPrice:78,volatility:.018,baseDrift:.0005,liquidity:72_000_000,spreadBps:7,fractional:true,benchmarkWeight:.06,exposures:{"ai-boom":.5,"sticky-inflation":.1,"rate-cut-rally":.35,"credit-stress":-.45,"supply-shock":.3,"crypto-risk-on":.05},macroSensitivity:sensitivity(.7,.1,-.35,-.5,.35,0)},
  {symbol:"HEAL",name:"Helix Health",assetClass:"stock",sector:"Healthcare",description:"Diversified diagnostics and therapeutics platform.",initialPrice:96,volatility:.014,baseDrift:.0004,liquidity:64_000_000,spreadBps:6,fractional:true,benchmarkWeight:.06,exposures:{"ai-boom":.1,"sticky-inflation":-.05,"rate-cut-rally":.2,"credit-stress":.15,"supply-shock":-.1,"crypto-risk-on":-.05},macroSensitivity:sensitivity(.2,-.1,-.15,-.05,-.05,0)},
  {symbol:"BANK",name:"Civic Bank",assetClass:"stock",sector:"Financials",description:"Commercial bank exposed to credit cycles and yield curves.",initialPrice:54,volatility:.022,baseDrift:.00035,liquidity:110_000_000,spreadBps:5,fractional:true,benchmarkWeight:.07,exposures:{"ai-boom":.25,"sticky-inflation":.15,"rate-cut-rally":.3,"credit-stress":-1.5,"supply-shock":-.35,"crypto-risk-on":.1},macroSensitivity:sensitivity(.8,.1,.35,-1.6,-.1,.05)},
  {symbol:"MOBI",name:"Motive Systems",assetClass:"stock",sector:"Industrials",description:"Autonomous logistics and mobility hardware.",initialPrice:63,volatility:.026,baseDrift:.00055,liquidity:58_000_000,spreadBps:9,fractional:true,benchmarkWeight:.05,exposures:{"ai-boom":.75,"sticky-inflation":-.4,"rate-cut-rally":.55,"credit-stress":-.8,"supply-shock":-.8,"crypto-risk-on":.1},macroSensitivity:sensitivity(1.1,-.5,-.65,-.75,-.35,.05)},
];
